// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8piH5C59BNISe6JTOesfVwOUtU017dEw',
    appId: '1:1030791735804:web:638533da3cc02b17ebaa79',
    messagingSenderId: '1030791735804',
    projectId: 'imhungry-8970e',
    authDomain: 'imhungry-8970e.firebaseapp.com',
    storageBucket: 'imhungry-8970e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBravO2IbpRuEk8DpX60i56G6x9BwfWy1w',
    appId: '1:1030791735804:android:13e263bc0a553120ebaa79',
    messagingSenderId: '1030791735804',
    projectId: 'imhungry-8970e',
    storageBucket: 'imhungry-8970e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr7DaBsyP-mtuxnsknFUj457AmQ9E-Nn8',
    appId: '1:1030791735804:ios:585457e2a7747917ebaa79',
    messagingSenderId: '1030791735804',
    projectId: 'imhungry-8970e',
    storageBucket: 'imhungry-8970e.appspot.com',
    iosBundleId: 'com.example.imHungry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr7DaBsyP-mtuxnsknFUj457AmQ9E-Nn8',
    appId: '1:1030791735804:ios:143d9a5b3e8633eaebaa79',
    messagingSenderId: '1030791735804',
    projectId: 'imhungry-8970e',
    storageBucket: 'imhungry-8970e.appspot.com',
    iosBundleId: 'com.example.imHungry.RunnerTests',
  );
}
